#ifndef EMACS_WGPU_FFI_H
#define EMACS_WGPU_FFI_H

/* Generated by cbindgen from rust/wgpu-backend. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status codes returned across the FFI boundary.
 */
#define WGPU_OK 0

#define WGPU_ERR_INIT -1

/**
 * Kind of input event. ABI-stable: values must not be reordered.
 */
typedef enum {
  WgpuEventKind_Key = 0,
  WgpuEventKind_Resize = 1,
  WgpuEventKind_FocusIn = 2,
  WgpuEventKind_FocusOut = 3,
} WgpuEventKind;

/**
 * A backend input event, ABI-stable for the C side.
 *
 * `a`/`b` are kind-dependent payload slots (kept generic so the C struct stays
 * fixed-size as event kinds gain fields):
 * - `Key`:    `a` = keysym, `b` = modifier mask
 * - `Resize`: `a` = width px, `b` = height px
 * - focus:    unused
 */
typedef struct {
  WgpuEventKind kind;
  uint32_t a;
  uint32_t b;
} WgpuEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the backend process-global state. Idempotent. Returns `WGPU_OK`
 * on success. M0: no-op scaffold.
 */
int wgpu_backend_init(void);

/**
 * Tear down process-global backend state. M0: no-op.
 */
void wgpu_backend_shutdown(void);

/**
 * Backend version string (static, NUL-terminated, owned by the backend).
 * The C side must not free it.
 */
const char *wgpu_backend_version(void);

/**
 * File descriptor Emacs should add to its `select` set to be woken when input
 * is available. Returns -1 until a window/event-thread exists (M0 always -1).
 */
int wgpu_backend_wakeup_fd(void);

/**
 * Drain up to `max` pending input events into the C-provided buffer `buf`,
 * returning the number written. Called from `read_socket_hook`.
 *
 * # Safety
 * `buf` must point to writable storage for at least `max` `WgpuEvent` values,
 * or be null when `max == 0`.
 */
int wgpu_backend_poll_events(WgpuEvent *buf, int max);

/**
 * Render an offscreen frame of `width`x`height` cleared to the given color
 * (linear RGBA, 0..=1) and write tightly-packed RGBA8 into `out` (which must
 * have room for `out_len` >= width*height*4 bytes). Returns `WGPU_OK` or a
 * negative error code. Used by the golden-image test harness.
 *
 * # Safety
 * `out` must point to writable storage of at least `out_len` bytes.
 */
int wgpu_render_clear_rgba(uint32_t width,
                           uint32_t height,
                           double r,
                           double g,
                           double b,
                           double a,
                           uint8_t *out,
                           uintptr_t out_len);

/**
 * Render an offscreen clear frame and write it as a PNG to `path`.
 * Returns `WGPU_OK` or a negative error code.
 *
 * # Safety
 * `path` must be a valid NUL-terminated C string.
 */
int wgpu_render_clear_to_png(const char *path,
                             uint32_t width,
                             uint32_t height,
                             double r,
                             double g,
                             double b,
                             double a);

/**
 * Begin a frame of `width`x`height` with the given clear color (linear RGBA).
 * Returns 0 on success, -1 if no GPU.
 */
int wgpu_frame_begin(uint32_t width, uint32_t height, double r, double g, double b, double a);

/**
 * Upload a `w`x`h` coverage bitmap (1 byte/pixel, row-major) into the glyph
 * atlas. Returns a glyph id (>= 0) for later `wgpu_frame_glyph` calls, or -1.
 *
 * # Safety
 * `data` must point to at least `len` readable bytes, `len >= w*h`.
 */
int64_t wgpu_atlas_upload(uint32_t w, uint32_t h, const uint8_t *data, uintptr_t len);

/**
 * Record a solid filled rectangle (pixels, linear RGBA).
 */
void wgpu_frame_rect(float x, float y, float w, float h, float r, float g, float b, float a);

/**
 * Record a glyph (by id from `wgpu_atlas_upload`) at pen position x,y, tinted.
 * The glyph is drawn at its uploaded pixel size.
 */
void wgpu_frame_glyph(int64_t id, float x, float y, float r, float g, float b, float a);

/**
 * Render the recorded frame offscreen and copy RGBA8 into `out`
 * (`>= width*height*4` bytes). Returns 0 / -1. Does not clear the commands,
 * so it may be called more than once per frame.
 *
 * # Safety
 * `out` must point to writable storage of at least `out_len` bytes.
 */
int wgpu_frame_end_rgba(uint8_t *out, uintptr_t out_len);

/**
 * Render the recorded frame offscreen and write it as a PNG to `path`.
 *
 * # Safety
 * `path` must be a valid NUL-terminated C string.
 */
int wgpu_frame_end_png(const char *path);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* EMACS_WGPU_FFI_H */
