#ifndef EMACS_WGPU_FFI_H
#define EMACS_WGPU_FFI_H

/* Generated by cbindgen from rust/wgpu-backend. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status codes returned across the FFI boundary.
 */
#define WGPU_OK 0

#define WGPU_ERR_INIT -1

/**
 * Modifier bits (our own encoding; translated to Emacs modifiers on the C
 * side).  Shift is reported but usually already baked into `unichar`.
 */
#define WGPU_MOD_SHIFT (1 << 0)

#define WGPU_MOD_CTRL (1 << 1)

#define WGPU_MOD_ALT (1 << 2)

#define WGPU_MOD_LOGO (1 << 3)

/**
 * Kind of input event. ABI-stable: values must not be reordered.
 */
typedef enum {
  WgpuEventKind_KeyPress = 0,
  WgpuEventKind_FocusIn = 1,
  WgpuEventKind_FocusOut = 2,
  /**
   * Pointer moved; x/y carry the surface-relative position.
   */
  WgpuEventKind_PointerMotion = 3,
  /**
   * Pointer button pressed; button/x/y are set.
   */
  WgpuEventKind_PointerPress = 4,
  /**
   * Pointer button released; button/x/y are set.
   */
  WgpuEventKind_PointerRelease = 5,
  /**
   * Scroll wheel/axis; axis_x/axis_y carry the (hi-res) deltas.
   */
  WgpuEventKind_PointerAxis = 6,
} WgpuEventKind;

/**
 * A backend input event, ABI-stable for the C side.
 */
typedef struct {
  WgpuEventKind kind;
  /**
   * xkb/X keysym (KeyPress).
   */
  uint32_t keysym;
  /**
   * Unicode codepoint, or 0 if the key produced no text (KeyPress).
   */
  uint32_t unichar;
  /**
   * Modifier mask (WGPU_MOD_*).
   */
  uint32_t modifiers;
  /**
   * Pointer position in surface pixels (PointerMotion/Press/Release).
   */
  int32_t x;
  int32_t y;
  /**
   * Emacs button number (0=left, 1=right, 2=middle, ...) for Press/Release.
   */
  uint32_t button;
  /**
   * Event timestamp in milliseconds (pointer events).
   */
  uint32_t time;
  /**
   * Hi-res scroll deltas (PointerAxis); +y scrolls down, +x scrolls right.
   */
  int32_t axis_x;
  int32_t axis_y;
} WgpuEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the backend process-global state. Idempotent. Returns `WGPU_OK`
 * on success. M0: no-op scaffold.
 */
int wgpu_backend_init(void);

/**
 * Tear down process-global backend state. M0: no-op.
 */
void wgpu_backend_shutdown(void);

/**
 * Backend version string (static, NUL-terminated, owned by the backend).
 * The C side must not free it.
 */
const char *wgpu_backend_version(void);

/**
 * File descriptor Emacs should add to its `select` set to be woken when input
 * is available. Returns -1 until a window/event-thread exists (M0 always -1).
 */
int wgpu_backend_wakeup_fd(void);

/**
 * Drain up to `max` pending input events into the C-provided buffer `buf`,
 * returning the number written. Called from `read_socket_hook`.
 *
 * # Safety
 * `buf` must point to writable storage for at least `max` `WgpuEvent` values,
 * or be null when `max == 0`.
 */
int wgpu_backend_poll_events(WgpuEvent *buf, int max);

/**
 * Render an offscreen frame of `width`x`height` cleared to the given color
 * (linear RGBA, 0..=1) and write tightly-packed RGBA8 into `out` (which must
 * have room for `out_len` >= width*height*4 bytes). Returns `WGPU_OK` or a
 * negative error code. Used by the golden-image test harness.
 *
 * # Safety
 * `out` must point to writable storage of at least `out_len` bytes.
 */
int wgpu_render_clear_rgba(uint32_t width,
                           uint32_t height,
                           double r,
                           double g,
                           double b,
                           double a,
                           uint8_t *out,
                           uintptr_t out_len);

/**
 * Render an offscreen clear frame and write it as a PNG to `path`.
 * Returns `WGPU_OK` or a negative error code.
 *
 * # Safety
 * `path` must be a valid NUL-terminated C string.
 */
int wgpu_render_clear_to_png(const char *path,
                             uint32_t width,
                             uint32_t height,
                             double r,
                             double g,
                             double b,
                             double a);

/**
 * Begin a frame of `width`x`height` with the given clear color (linear RGBA).
 * Returns 0 on success, -1 if no GPU.
 */
int wgpu_frame_begin(uint32_t width, uint32_t height, double r, double g, double b, double a);

/**
 * Upload a `w`x`h` coverage bitmap (1 byte/pixel, row-major) into the glyph
 * atlas. Returns a glyph id (>= 0) for later `wgpu_frame_glyph` calls, or -1.
 *
 * # Safety
 * `data` must point to at least `len` readable bytes, `len >= w*h`.
 */
int64_t wgpu_atlas_upload(uint32_t w, uint32_t h, const uint8_t *data, uintptr_t len);

/**
 * Record a solid filled rectangle (pixels, linear RGBA).
 */
void wgpu_frame_rect(float x, float y, float w, float h, float r, float g, float b, float a);

/**
 * Record a glyph (by id from `wgpu_atlas_upload`) at pen position x,y, tinted.
 * The glyph is drawn at its uploaded pixel size.
 */
void wgpu_frame_glyph(int64_t id, float x, float y, float r, float g, float b, float a);

/**
 * Render the recorded frame offscreen and copy RGBA8 into `out`
 * (`>= width*height*4` bytes). Returns 0 / -1. Does not clear the commands,
 * so it may be called more than once per frame.
 *
 * # Safety
 * `out` must point to writable storage of at least `out_len` bytes.
 */
int wgpu_frame_end_rgba(uint8_t *out, uintptr_t out_len);

/**
 * Render the recorded frame offscreen and write it as a PNG to `path`.
 *
 * # Safety
 * `path` must be a valid NUL-terminated C string.
 */
int wgpu_frame_end_png(const char *path);

/**
 * Open the (single) Emacs window. `title` is a NUL-terminated C string (may be
 * null for a default). Returns 0 on success, -1 on failure.
 *
 * # Safety
 * `title`, if non-null, must be a valid NUL-terminated C string.
 */
int wgpu_window_open(const char *title);

/**
 * Wayland connection fd for Emacs to select on. -1 if no window.
 */
int wgpu_window_fd(void);

/**
 * Key-repeat timerfd for Emacs to select on (so it wakes to emit repeats).
 * -1 if unavailable.
 */
int wgpu_window_timer_fd(void);

/**
 * Process pending Wayland events. Returns 1 if the compositor asked the
 * window to close, else 0 (negative on error).
 */
int wgpu_window_dispatch(void);

/**
 * Integer output scale factor (1, 2, ...) for HiDPI. 1 if no window.
 */
int wgpu_window_scale(void);

/**
 * Current window size in pixels, written to *w/*h.
 *
 * # Safety
 * `w` and `h` must be valid pointers.
 */
void wgpu_window_size(uint32_t *w, uint32_t *h);

/**
 * Upload a coverage glyph (w*h bytes) into the window's atlas; returns id >=0.
 *
 * # Safety
 * `data` must point to at least `len >= w*h` readable bytes.
 */
int64_t wgpu_window_atlas_upload(uint32_t w, uint32_t h, const uint8_t *data, uintptr_t len);

/**
 * Drain up to `max` pending input events into `buf`; returns the count.
 * Called from read_socket_hook.
 *
 * # Safety
 * `buf` must point to writable storage for at least `max` `WgpuEvent`s.
 */
int wgpu_window_poll_events(WgpuEvent *buf, int max);

/**
 * Begin a redisplay batch.  NOTE: this must NOT clear the command list --
 * Emacs calls update_begin per window/region (many times) with a single
 * frame_up_to_date at the end; clearing here would drop all but the last
 * update and cause heavy artifacting.  Commands accumulate and are cleared by
 * `present` after they are composited onto the persistent texture.
 */
void wgpu_window_begin(void);

/**
 * Record a solid filled rectangle (pixels, linear RGBA 0..=1).
 */
void wgpu_window_rect(float x, float y, float w, float h, float r, float g, float b, float a);

/**
 * Record a glyph (atlas id from `wgpu_window_atlas_upload`) at x,y, tinted.
 */
void wgpu_window_glyph(int64_t id, float x, float y, float r, float g, float b, float a);

/**
 * Composite the recorded commands and present to the window.
 */
void wgpu_window_present(void);

/**
 * Scroll the region [x, from_y, w, h] of the persistent frame to [x, to_y].
 * Called from scroll_run before the newly-exposed lines are drawn.
 */
void wgpu_window_scroll(int x, int from_y, int w, int h, int to_y);

/**
 * If the compositor asked for a new size since the last call, write it to
 * *w/*h and return 1; else return 0. Emacs calls this from read_socket and
 * resizes the frame accordingly.
 *
 * # Safety
 * `w` and `h` must be valid pointers.
 */
int wgpu_window_take_resize(uint32_t *w, uint32_t *h);

/**
 * Read the window's current frame (persistent texture) back and write it as a
 * PNG to `path`.  For clarity inspection / real-text golden tests.
 *
 * # Safety
 * `path` must be a valid NUL-terminated C string.
 */
int wgpu_window_dump_png(const char *path);

/**
 * Destroy the window and release GPU/Wayland resources.
 */
void wgpu_window_close(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* EMACS_WGPU_FFI_H */
