#ifndef EMACS_WLSHM_FFI_H
#define EMACS_WLSHM_FFI_H

/* Generated by cbindgen from rust/wlshm-backend. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status codes returned across the FFI boundary.
 */
#define WLSHM_OK 0

#define WLSHM_ERR_INIT -1

/**
 * Modifier bits (our own encoding; translated to Emacs modifiers on the C
 * side).  Shift is reported but usually already baked into `unichar`.
 */
#define WLSHM_MOD_SHIFT (1 << 0)

#define WLSHM_MOD_CTRL (1 << 1)

#define WLSHM_MOD_ALT (1 << 2)

#define WLSHM_MOD_LOGO (1 << 3)

/**
 * Kind of input event. ABI-stable: values must not be reordered.
 */
typedef enum {
  WlshmEventKind_KeyPress = 0,
  WlshmEventKind_FocusIn = 1,
  WlshmEventKind_FocusOut = 2,
  /**
   * Pointer moved; x/y carry the surface-relative position.
   */
  WlshmEventKind_PointerMotion = 3,
  /**
   * Pointer button pressed; button/x/y are set.
   */
  WlshmEventKind_PointerPress = 4,
  /**
   * Pointer button released; button/x/y are set.
   */
  WlshmEventKind_PointerRelease = 5,
  /**
   * Scroll wheel/axis; axis_x/axis_y carry the (hi-res) deltas.
   */
  WlshmEventKind_PointerAxis = 6,
  /**
   * Compositor asked the window to resize; x/y carry the new w/h (pixels).
   */
  WlshmEventKind_Configure = 7,
  /**
   * Compositor asked the window to close.
   */
  WlshmEventKind_Close = 8,
  /**
   * A drag-and-drop drop occurred; x/y carry the surface-relative drop
   * position, `window` the target.  The dropped payload (text or
   * `text/uri-list`) is retrieved via a side-channel getter on the C side
   * (`wlshm_window_get_drop`) because the POD event can't carry a string.
   * `button` is reused as a flag: 1 = the payload is a `text/uri-list`.
   */
  WlshmEventKind_Drop = 9,
  /**
   * The IME (zwp_text_input_v3) updated the in-progress composition
   * (preedit) string.  The text itself is retrieved via a side-channel
   * getter (`wlshm_window_get_preedit`) because the POD event can't carry a
   * string; an empty string clears the preedit.  Committed (final) IME text
   * is delivered separately as ordinary `KeyPress` events, one per
   * codepoint, so it flows through the normal keystroke path.
   */
  WlshmEventKind_Preedit = 10,
  /**
   * The pointer left the surface; the C side clears any lingering mouse-face
   * highlight so it doesn't persist until the next redisplay.
   */
  WlshmEventKind_PointerLeave = 11,
} WlshmEventKind;

/**
 * A backend input event, ABI-stable for the C side.
 */
typedef struct {
  WlshmEventKind kind;
  /**
   * xkb/X keysym (KeyPress).
   */
  uint32_t keysym;
  /**
   * Unicode codepoint, or 0 if the key produced no text (KeyPress).
   */
  uint32_t unichar;
  /**
   * Modifier mask (WLSHM_MOD_*).
   */
  uint32_t modifiers;
  /**
   * Pointer position in surface pixels (PointerMotion/Press/Release).
   */
  int32_t x;
  int32_t y;
  /**
   * Emacs button number (0=left, 1=right, 2=middle, ...) for Press/Release.
   */
  uint32_t button;
  /**
   * Event timestamp in milliseconds (pointer events).
   */
  uint32_t time;
  /**
   * Hi-res scroll deltas (PointerAxis); +y scrolls down, +x scrolls right.
   */
  int32_t axis_x;
  int32_t axis_y;
  /**
   * Opaque window handle this event belongs to (0 = unknown/primary).
   */
  uint64_t window;
} WlshmEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the backend process-global state. Idempotent. Returns `WLSHM_OK`.
 */
int wlshm_backend_init(void);

/**
 * Tear down process-global backend state. No-op.
 */
void wlshm_backend_shutdown(void);

/**
 * Backend version string (static, NUL-terminated, owned by the backend).
 * The C side must not free it.
 */
const char *wlshm_backend_version(void);

/**
 * Open a window; returns an opaque handle (0 on failure).  Lazily connects to
 * Wayland on the first call.  `title` may be null.  `kind`: 0=Toplevel,
 * 1=Popup, 2=Tooltip.  `parent` is a handle or 0.
 *
 * # Safety
 * `title`, if non-null, must be a valid NUL-terminated C string.
 */
uint64_t wlshm_window_open(const char *title, uint64_t parent, uint32_t kind);

/**
 * Ensure a Wayland connection exists (without opening a window).  Returns 0 on
 * success, -1 on failure.  Lets term-init learn the output scale early.
 */
int wlshm_backend_connect(void);

/**
 * Wayland connection fd for Emacs to select on. -1 if not connected.
 */
int wlshm_window_fd(void);

/**
 * Key-repeat timerfd for Emacs to select on. -1 if unavailable.
 */
int wlshm_window_timer_fd(void);

/**
 * The present-deadline timerfd; Emacs adds it as a keyboard wait descriptor so
 * its firing wakes read_socket -> dispatch -> flush_overdue_pending().
 */
int wlshm_window_present_timer_fd(void);

/**
 * Disarm the key-repeat timer and forget the held key.  The C side calls this
 * when entering/leaving a modal popup loop, so a key held during the menu does
 * not keep repeating into the main loop after the menu closes.
 */
void wlshm_window_disarm_repeat(void);

/**
 * Process pending Wayland events. Returns 0 normally, negative on error.
 * (Window-close arrives as a Close event via poll_events.)
 */
int wlshm_window_dispatch(void);

/**
 * Rounded integer scale factor of window `win` (1 = default).  Kept for
 * callers (e.g. Emacs DPI/resolution) that want a plain integer; the precise
 * fractional value is `wlshm_window_scale120`.
 */
int wlshm_window_scale(uint64_t win);

/**
 * Scale factor of window `win` times 120 (the wp_fractional_scale_v1 unit).
 * 120 == 1.0, 180 == 1.5x, 240 == 2.0x.  The C side multiplies the logical
 * surface size by this/120 to size its physical-pixel Cairo canvas, and sets
 * the Cairo device scale to this/120 so all drawing stays in logical
 * coordinates yet rasterizes at physical resolution.
 */
uint32_t wlshm_window_scale120(uint64_t win);

/**
 * Current size of window `win` in pixels, written to *w/*h.
 *
 * # Safety
 * `w` and `h` must be valid pointers.
 */
void wlshm_window_size(uint64_t win, uint32_t *w, uint32_t *h);

/**
 * Drain up to `max` pending input events into `buf`; returns the count.
 *
 * # Safety
 * `buf` must point to writable storage for at least `max` `WlshmEvent`s.
 */
int wlshm_window_poll_events(WlshmEvent *buf, int max);

/**
 * Present window `win`'s Cairo canvas (XRGB8888, `src_w`x`src_h`, `src_stride`
 * bytes/row) into a free wl_shm buffer sized to the SOURCE.  Zero damage rect
 * means whole surface.
 *
 * # Safety
 * `src` must point to at least `src_h * src_stride` readable bytes.
 */
void wlshm_window_present(uint64_t win,
                          const uint8_t *src,
                          uint32_t src_w,
                          uint32_t src_h,
                          uint32_t src_stride,
                          int dmg_x,
                          int dmg_y,
                          int dmg_w,
                          int dmg_h);

/**
 * Set window `win`'s title.  `title` is a NUL-terminated C string.
 *
 * # Safety
 * `title` must be a valid NUL-terminated C string.
 */
void wlshm_window_set_title(uint64_t win, const char *title);

/**
 * Set the pointer cursor shape (codes match the C `wlshm_cursor_shape` enum).
 * Cursor is per-seat, so `win` is advisory.
 */
void wlshm_window_set_cursor(uint64_t _win, int code);

/**
 * If window `win` has a pending resize, write it to *w/*h and return 1.
 *
 * # Safety
 * `w` and `h` must be valid pointers.
 */
int wlshm_window_take_resize(uint64_t win, uint32_t *w, uint32_t *h);

/**
 * Close (destroy) window `win`.
 */
void wlshm_window_close(uint64_t win);

/**
 * Set `win`'s geometry AND position.  For a Pending popup/tooltip this CREATES
 * the xdg_popup anchored at (x,y) in the parent's geometry with content size
 * (w,h) — so it floats over the parent (never tiled) and is placed precisely.
 * For an already-mapped popup it repositions it to (x,y) (e.g. a reused tooltip
 * following the pointer).  For a toplevel it just records the size (the next
 * present allocates a buffer of that size).
 *
 * NOTE: this is the *positioned* entry point.  Frame-size requests that carry
 * no meaningful position (the set_window_size hook) must use
 * `wlshm_window_set_size` instead, or a tooltip would be created/anchored at a
 * bogus (0,0) before its real position has been computed.
 */
void wlshm_window_set_geometry(uint64_t win, int x, int y, int w, int h);

/**
 * Set `win`'s content size WITHOUT touching its position.  Used by the
 * set_window_size hook, which has no position to offer.  A Pending popup is
 * left Pending (it becomes a real popup only via the positioned
 * `wlshm_window_set_geometry`), so a tooltip is never anchored at (0,0) before
 * `compute_tip_xy` has run.
 */
void wlshm_window_set_size(uint64_t win, int w, int h);

/**
 * Position child subsurface `win` at (x, y) LOGICAL pixels relative to its
 * parent frame.  No-op for non-subsurface windows (Wayland forbids a client
 * positioning its own toplevel).  Placement applies on the parent's commit.
 */
void wlshm_window_set_subsurface_pos(uint64_t win, int x, int y);

/**
 * Reparent `win` to `parent` (xdg_toplevel.set_parent).  `parent` 0 clears it.
 */
void wlshm_window_set_parent(uint64_t win, uint64_t parent);

/**
 * Minimize `win` (xdg_toplevel.set_minimized).
 */
void wlshm_window_minimize(uint64_t win);

/**
 * Set/unset fullscreen for `win`. `mode`: 0=off, 1=on.
 */
void wlshm_window_set_fullscreen(uint64_t win, int mode);

/**
 * Toggle server-side decorations on `win`.  Decorations are chosen at window
 * creation (WindowDecorations); a reliable runtime toggle needs xdg-decoration
 * renegotiation that most compositors only honor at map time, so this is a
 * documented best-effort no-op for now (undecorated tooltip/menu/child frames
 * already get created without decorations).
 */
void wlshm_window_set_decorations(uint64_t _win, bool _on);

/**
 * Hide/show the hardware pointer over `win` (Emacs hides it while typing).
 * Hidden = attach a null cursor surface; shown = re-assert our cursor shape.
 */
void wlshm_window_hide_pointer(uint64_t _win, bool hide);

/**
 * Unmap `win` (hide it) by committing a null buffer.  Re-present to remap.
 */
void wlshm_window_unmap(uint64_t win);

/**
 * Number of connected outputs (monitors).
 */
int wlshm_output_count(void);

/**
 * Geometry of output `idx` for display-monitor-attributes-list.  Writes
 * logical x/y and px w/h, physical mm w/h, integer scale, and the NUL-
 * terminated name (truncated to `name_cap`).  Returns 1 on success.
 *
 * # Safety
 * Output pointers, if non-null, must be writable; `name` must have room for
 * `name_cap` bytes.
 */
int wlshm_output_get(int idx,
                     int *x,
                     int *y,
                     int *w,
                     int *h,
                     int *mm_w,
                     int *mm_h,
                     int *scale,
                     char *name,
                     uintptr_t name_cap);

/**
 * Take ownership of the CLIPBOARD selection with `len` bytes at `data`.
 *
 * # Safety
 * `data` must point to at least `len` readable bytes.
 */
int wlshm_window_set_clipboard(const uint8_t *data, uintptr_t len);

/**
 * Read the CLIPBOARD selection.  Writes a pointer/length valid until the next
 * call into *out_ptr/*out_len and returns 0; -1 if empty.
 *
 * # Safety
 * `out_ptr` and `out_len` must be valid pointers.
 */
int wlshm_window_get_clipboard(const uint8_t **out_ptr, uintptr_t *out_len);

/**
 * Retrieve the payload of the most recently delivered Drop event.  Writes a
 * pointer/length valid until the next call into *out_ptr/*out_len and returns
 * 0; -1 if there is no pending drop text.  C must call this right after it pops
 * a `WlshmEventKind_Drop` event (whose `.button` flags a `text/uri-list`).
 *
 * # Safety
 * `out_ptr` and `out_len` must be valid pointers.
 */
int wlshm_window_get_drop(const uint8_t **out_ptr, uintptr_t *out_len);

/**
 * Retrieve the current IME preedit (composition) string.  Writes a
 * pointer/length valid until the next call into *out_ptr/*out_len and returns
 * 0; -1 if there is no preedit object at all.  The buffer is UTF-8 and may be
 * empty (length 0) to mean "clear the preedit".  C must call this right after
 * it pops a `WlshmEventKind_Preedit` event.
 *
 * # Safety
 * `out_ptr` and `out_len` must be valid pointers.
 */
int wlshm_window_get_preedit(const uint8_t **out_ptr, uintptr_t *out_len);

/**
 * Release our ownership of the CLIPBOARD selection.
 */
void wlshm_window_disown_clipboard(void);

/**
 * 1 if we own the CLIPBOARD selection, else 0.
 */
int wlshm_window_owns_clipboard(void);

/**
 * 1 if a CLIPBOARD selection exists (we or another client own it), else 0.
 */
int wlshm_window_clipboard_exists(void);

/**
 * Take ownership of the PRIMARY selection with `len` bytes at `data`.
 *
 * # Safety
 * `data` must point to at least `len` readable bytes.
 */
int wlshm_window_set_primary(const uint8_t *data, uintptr_t len);

/**
 * Read the PRIMARY selection.  Writes a pointer/length valid until the next
 * call into *out_ptr/*out_len and returns 0; -1 if empty.
 *
 * # Safety
 * `out_ptr` and `out_len` must be valid pointers.
 */
int wlshm_window_get_primary(const uint8_t **out_ptr, uintptr_t *out_len);

/**
 * Release our ownership of the PRIMARY selection.
 */
void wlshm_window_disown_primary(void);

/**
 * 1 if we own the PRIMARY selection, else 0.
 */
int wlshm_window_owns_primary(void);

/**
 * 1 if a PRIMARY selection exists (we or another client own it), else 0.
 */
int wlshm_window_primary_exists(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* EMACS_WLSHM_FFI_H */
